### ISSUE TITLE
inline function will error in android jni

### ISSUE THREAD

**Issue by fatalfeel** [kcat/openal-soft#107] opened 2017-04-27 01:37 UTC
Build openal in android platform use inline function will have a lot error
if could change all of them to normal function
![1](https://cloud.githubusercontent.com/assets/1575549/25464082/1897d854-2b2d-11e7-9dc7-0a26f856af7a.png)

**Comment by fatalfeel** [comment] 2017-04-27 01:43
suggest inline function in xxx.c and extern in xxx.h
ex:
inline ALfloat minf(ALfloat a, ALfloat b)
{ return ((a > b) ? b : a); }     //in alu.c

and

extern ALfloat minf(ALfloat a, ALfloat b);  //in alu.h

**Comment by kcat** [comment] 2017-04-27 01:55
Looks like the compiler isn't properly configured for C99. Inlining is used according to C99 rules, and it works fine on GCC and Clang (and MSVC too, which doesn't otherwise do C99). I can remove inlining of specific functions where it's shown to improve performance, but not all of them. Sorry.

Can you provide more details about your compiler, and CMake's output when configuring OpenAL Soft?

**Comment by fatalfeel** [comment] 2017-04-27 03:14
here i modify for android platform replace inline function to .c
http://www.mediafire.com/file/v9n1055k4bhs3m8/openal_android_20170407.tar.gz

**Comment by kcat** [comment] 2017-04-27 09:36
That's not what I asked for. I'm sorry, but I'm not going to remove inline functions without a good reason. It's used according to the C standard, and works in at least GCC, Clang, and MSVC. If it doesn't work for you, I need to know more about your compiler setup to figure out what's wrong.

**Comment by fatalfeel** [comment] 2017-04-27 12:48
in android 5.0 / 6.0 .....We can build the openal in App layer or android framework/media   layer
The arm-linux-gcc not support inline in the .h file~~~ if want to cross-platform in android
suggest inline function to the .c and .h use extern~~~
I modify it ok... and build done in the link address

**Comment by fatalfeel** [comment] 2017-04-27 12:59
kcat you can install cygwin and eclipse and android dev plugin and c++ dev plugin and
android platform sdk and android ndk to build in jni and java will know arm-linux-gnueabi-gcc can not build
inline in .h

**Comment by kcat** [comment] 2017-04-27 13:20
GCC does support inline functions for arm-linux, as I use that to test cross-compiling to Android. What version of GCC is it? What was the output of CMake?

**Comment by fatalfeel** [comment] 2017-04-27 21:10
Its not use Cmake to build... use android.mk to build

**Comment by kcat** [comment] 2017-04-30 08:42
> Its not use Cmake to build... use android.mk to build

That's probably why, then, since cmake configures the build to use the appropriate compiler switches. Specifically, ```-std=c99``` or ```-std=c11``` and ```-fno-gnu89-inline``` as needed. You should really let cmake run so OpenAL Soft can build properly; even if this helps, who knows what else may be broken or sub-optimal without cmake properly configuring it.

With Android Studio, you can make OpenAL Soft a sub-project of your main project, so it should configure and build correctly as part of your project (Android Studio uses cmake nowadays, so you can modify your project's ```CMakeLists.txt``` to do something like ```add_subdirectory("${CMAKE_SOURCE_DIR}/openal-soft")```, depending on where OpenAL Soft's code is relative to your project's).

I'm closing this since it's not a problem with OpenAL Soft's inline functions or configuration. But if you still have more questions relating to this, ask them here and I'll try to help if I can.

**Closed by kcat** 2017-04-30 08:42 UTC

**Comment by fatalfeel** [comment] 2017-04-30 12:35
android C not support keyword "restrict"  either...

**Comment by kcat** [comment] 2017-04-30 12:43
The restrict keyword is C99 too. The issue is the same as with inline.

**Comment by fatalfeel** [comment] 2017-04-30 19:45
I can help u all inline move to C if you want ... in this code done it...can compare code and move it..
http://www.mediafire.com/file/v9n1055k4bhs3m8/openal_android_20170407.tar.gz
