### ISSUE TITLE
althrd_starter data race

### ISSUE THREAD

**Issue by galek** [kcat/openal-soft#7] opened 2015-04-05 10:54 UTC
Hi
i found data race in thread althrd_starter.

detected using vs2015 and VTune.

In my engine used task based threading.
and updating listener position is task

**Comment by kcat** [comment] 2015-04-05 16:30
I'm not sure I see where the race condition is in althrd_starter. Can you clarify what the problem is?

**Comment by galek** [comment] 2015-04-06 20:37
I found it using  the package VTune, or Visual studio profiler.
Just  this detected is regularly.

If I will remove thread support ,much do I lose?I honestly did not delve into the code of OpenAL..

**Comment by kcat** [comment] 2015-04-07 21:51
OpenAL Soft requires threading to do background processing, including audio mixing.

Does VTune or the Visual Studio Profiler describe what the race condition is? I'm still not able to see the problem.

**Comment by galek** [comment] 2015-08-12 22:22
sorry me for long time.

VS-profiler says what race with main thread. 

Xm, I will check how fixed this problem-so maybe problems from my implementation  of threads (It's based on Task-Based model. Updating audio is another task)

**Comment by galek** [comment] 2016-02-10 22:41
sorry me for long time, again, but problem is still on 1.17.1

Compiler: VS2015 update 1

So how i can make own solution for mixing?(I have own system of threads)

**Comment by kcat** [comment] 2016-02-11 04:11
Unfortunately I still don't know what the issue is. ```althrd_starter``` is just a launchpad function, it's given to the WinAPI thread function (```CreateThread```) and in turn calls the caller-supplied function. I don't see any race condition in the code. What information you can give me about where the problem is? Line numbers, conditions, execution order, callers, etc, would be helpful.

**Comment by kcat** [comment] 2017-05-28 08:12
Closing due to lack of information on what the problem actually is. All tests I've done check out fine, and there's no information here to show where there's a problem.

**Closed by kcat** 2017-05-28 08:12 UTC
