### ISSUE TITLE
Sound issue in S.T.A.L.K.E.R.: CoC/CoM

### ISSUE THREAD

**Issue by vmech** [kcat/openal-soft#174] opened 2018-03-06 06:04 UTC
Sounds good for OpenAL Soft output with default soft_oal.dll 1.17.2, but totally issued by cracklings for any versions above 1.17.2 . Why this happens?

Win 10 x64 1607 (10.0.14393), SB Audigy SE (SB0570). Checks tried with both WindowsUpdate driver update and Daniel K P17X Series Support Pack 3.1.

**Comment by kcat** [comment] 2018-03-06 17:32
Do the Stalker games use OpenAL? Are you sure it's using OpenAL Soft specifically, and not some other OpenAL driver?

Do other OpenAL apps have crackling when using 1.18.2, and can you get a recording of it?

**Comment by vmech** [comment] 2018-03-07 04:47
Of course I'm sure.

https://image.prntscr.com/image/Ob4J0NOsRGKYXy3WvTbtew.png
https://image.prntscr.com/image/cQT5xb0JRu_Z_lNtpLsMbQ.png
https://image.prntscr.com/image/jYOtUrjIQc2BXWkfrqhI6g.png
^^^ It's a default 1.17.2 32-bit soft_oal.dll in game binaries.

I dont know how I can record a sound output from game, Creative just cut out StereoMix (WhatUHear) from the driver.

**Comment by Krakean** [comment] 2018-03-10 21:32
@vmech may be you can at least provide link to source code, so author can try to compile it himself and check?

**Comment by kcat** [comment] 2018-03-10 22:10
I believe the Stalker games are still commercial, and I haven't heard of it going open source. As for other games that use OpenAL, on the free side of things that I can think of off the top of my head, there is the Amnesia: Dark Descent demo, Super Tux Kart (I believe there's a Windows version, perhaps?), and the open source version of Lugaru.

**Comment by Krakean** [comment] 2018-03-10 23:01
@kcat Stalker went open source :) Accidentally, though. But Studio head then said like a do whatever  you want with source code since it's leaked, but just do not make commercial games using it.

**Comment by Krakean** [comment] 2018-03-10 23:01
You can even found it on github. Called xray, usually

**Comment by vmech** [comment] 2018-03-11 22:05
https://github.com/OpenXRay

**Comment by kcat** [comment] 2018-03-11 22:53
I can't see anything wrong with the code that would cause crackling. I am a bit curious how it determines when a sound is finished playing since it doesn't seem to ever stop trying to read and queue audio, and doesn't have a way to check if the source finishes what it last queued, but that wouldn't cause any problems in the new version over the old one.

Regarding recording the output, I believe Windows provides built-in functionality for capturing what a playback device is playing. On Linux, these devices are normally called `"Monitor of <playback device name>"`, and Windows should have something similar.

**Comment by vmech** [comment] 2018-03-17 22:20
Виноват OpenAL, если активировать вывод через него, то он меняет у со-процессора режим округления с "до ближайшего", на "в меньшую сторону". Поскольку 32-битные числа с плавающей точкой представляются неточно, например, 4 может быть представлено как 3.9999999(9), то переключение режима округления все напрочь ломает - вместо 4-х мы получаем 3, но 3 представляется как 2.99(9), и так до 0. 64-битные типы данных такой проблемы не имеют, однако работают медленнее. По правилам хорошего тона: если меняешь режимы работы со-процессора, то должен вернуть их значения обратно, как только твои расчеты выполнены. OpenAL же ведет себя по-хамски.

**Comment by kcat** [comment] 2018-03-17 22:32
> Виноват OpenAL, если активировать вывод через него, то он меняет у со-процессора режим округления с "до ближайшего", на "в меньшую сторону".

According to Google translate, this says "OpenAL is to blame, if you activate the output through it, it changes the rounding mode from co-processor from "to the nearest", to "to the smaller side"."

That's partly true. Older versions of OpenAL Soft had a bug on Windows which left the FPU in "round to zero" mode after certain calls, affecting the calling thread. The latest 1.18.2 release actually fixes that, and restores the original FPU mode before returning.

**Comment by vmech** [comment] 2018-03-30 10:19
I found video on youtube with same sound cracklings which I got in CoC/CoM with openal-soft versions higher than 1.17.2
https://www.youtube.com/watch?v=kUC9m6PZ5MU

**Comment by kcat** [comment] 2018-03-30 20:56
Do you mean crackling as in occasional light static, or that it keeps breaking to silence?

**Comment by kcat** [comment] 2018-04-01 15:17
Try disabling the output limiter (you may also want to reduce the game's overall volume to prevent too much clipping distortion). Either, in `alsoft-config` toggle the Gain Limiter option off, or create/edit `%AppData%\alsoft.ini` and set:
`
[general]
output-limiter=false
`
You can also adjust the output volume from OpenAL Soft's side by setting:
`
[general]
volume-adjust = -6
`
(the value is in decibels).

**Comment by vmech** [comment] 2018-04-01 19:50
https://image.prntscr.com/image/r1wI_9l-TR_nj1xJE4ye-Q.png
> The changes from 1.17.2 include:
> Reduced the default period count to 3 (down from 4).

```
[General]
periods=4 
```
This option resolve problem with all sound artefacts. Thank you for the tip-off.

**Comment by kcat** [comment] 2018-04-01 20:36
Can you paste the full trace log from OpenAL Soft? Set the `ALSOFT_LOGLEVEL` environment variable to `3` to make OpenAL Soft print information to stderr about what it's doing. You can also set `ALSOFT_LOGFILE` to a full path+filename to have it write the info in the given file instead (just make sure it's a place you have write permission for).

3 periods should be plenty for most normal systems, so if it's causing trouble it would be helpful to know what's happening.

**Comment by vmech** [comment] 2018-04-01 21:32
Done.
[alsoft-logs.zip](https://github.com/kcat/openal-soft/files/1866723/alsoft-logs.zip)

**Comment by kcat** [comment] 2018-04-02 00:09
Well, the most notable thing is that for some reason, COM fails to initialize for the mmdevapi/wasapi backend. Error `0x80010106`, `RPC_E_CHANGED_MODE`, as a result of trying to initialize single-threaded COM after multithreaded COM was already initialized for the given thread.

That's extremely odd though, since OpenAL Soft is careful to only use COM on its own threads where the app shouldn't be able to interfere. The library creates a thread to handle COM stuff, and the first thing it does is call `CoInitialize` to initialize COM. I can only presume the game does something silly like hook thread creation and force multithreaded COM initialization on all created threads, which causes `CoInitialize` call to fail.

However, while that's not ideal, it shouldn't be the cause of any audible glitches. It correctly falls back to the DirectSound backend which should work. But maybe the combination of the smaller buffer size, along with it being emulated (with Vista and newer, DSound is software-driven on top of WASAPI), causes timing problems for the notification events, in turn causing OpenAL Soft's updates to be late or nearly-late which makes the crackling sound.

In either case, I pushed commit 414b56edec5441211dc924fef365c54267c04f1c which should allow the mmdevapi/wasapi backend to work with the game, and hopefully not be an issue with the default buffer metrics.

**Comment by vmech** [comment] 2018-04-02 01:37
Theoretically, I understand.

I can add one more detail: the X-Ray Engine itself is single-threaded. But in a multi-threaded Windows environment, the process scheduler assigns all available physical cores to the game process. And despite this, the game process continues to use only one physical core. This is clearly visible in the Task Manager.

Apparently these two "features" of game engine and OS cause a conflict of initialization COM.

Maybe you can make 32-bit dll with this pushed commit [414b56e](https://github.com/kcat/openal-soft/commit/414b56edec5441211dc924fef365c54267c04f1c), I could check how it works.

**Comment by kcat** [comment] 2018-04-02 02:32
> I can add one more detail: the X-Ray Engine itself is single-threaded. But in a multi-threaded Windows environment, the process scheduler assigns all available physical cores to the game process. And despite this, the game process continues to use only one physical core. This is clearly visible in the Task Manager.

That's normal (and default) behavior for apps. Assigning all available cores to the process simply means that whenever a thread in the process is running, that thread can be placed on any core the system has. A single-threaded app is simply an app that never calls `CreateThread` or similar, and so only has a single thread of execution (the main thread, that `main`/`WinMain` gets called on). It can't be executing code on more than one core at a given time, but the scheduler is free to move execution of that thread to whatever core it wants whenever it wants.

OpenAL Soft calls `CreateThread` to launch threads for itself, so that it can work asynchronously from the app's other thread(s). That shouldn't cause any problems for COM. Each thread maintains its own state for how COM is set up, and that state remains regardless of which core it's currently executing on.

> Maybe you can make 32-bit dll with this pushed commit 414b56e, I could check how it works.

This should be it: [soft_oal.dll.zip](https://github.com/kcat/openal-soft/files/1866926/soft_oal.dll.zip).

**Comment by vmech** [comment] 2018-04-02 03:10
Yep, it works properly. Sound artefacts absent.
```
AL lib: (II) alc_initconfig: Initializing library v1.18.2-414b56ed master
AL lib: (II) alc_initconfig: Supported backends: wasapi, dsound, winmm, null, wave
AL lib: (II) ReadALConfig: Loading config C:\Users\sCreamER\AppData\Roaming\alsoft.ini...
AL lib: (II) GetProcBinary: Got path: F:\GAMES\STALKER-CoM-10d\bin
AL lib: (II) ReadALConfig: Loading config F:\GAMES\STALKER-CoM-10d\bin\alsoft.ini...
AL lib: (II) GetConfigValue: Key disable-cpu-exts not found
AL lib: (II) FillCPUCaps: Detected max CPUID function: 0x5 (ext. 0x8000001b)
AL lib: (II) FillCPUCaps: Vendor ID: "AuthenticAMD"
AL lib: (II) FillCPUCaps: Name: "AMD Phenom(tm) II X4 965 Processor"
AL lib: (II) FillCPUCaps: Extensions: +SSE +SSE2 +SSE3 -SSE4.1
AL lib: (II) GetConfigValue: Key rt-prio not found
AL lib: (II) GetConfigValue: Key resampler not found
AL lib: (II) GetConfigValue: Key trap-al-error not found
AL lib: (II) GetConfigValue: Key trap-alc-error not found
AL lib: (II) GetConfigValue: Key reverb/boost not found
AL lib: (II) GetConfigValue: Key drivers not found
AL lib: (II) ALCwasapiProxy_messageHandler: Starting message thread
AL lib: (II) ALCwasapiProxy_messageHandler: Message thread initialization complete
AL lib: (II) ALCwasapiProxy_messageHandler: Starting message loop
AL lib: (II) alc_initconfig: Initialized backend "wasapi"
AL lib: (II) alc_initconfig: Added "wasapi" for playback
AL lib: (II) alc_initconfig: Added "wasapi" for capture
AL lib: (II) GetConfigValue: Key excludefx not found
AL lib: (II) GetConfigValue: Key default-reverb not found
AL lib: (II) GetConfigValue: Key channels not found
AL lib: (II) GetConfigValue: Key sample-type not found
AL lib: (II) GetConfigValue: Key frequency not found
AL lib: (II) GetConfigValue: Key periods not found
AL lib: (II) GetConfigValue: Key period_size not found
AL lib: (II) GetConfigValue: Key sources not found
AL lib: (II) GetConfigValue: Key slots not found
AL lib: (II) GetConfigValue: Key sends not found
AL lib: (II) ALCwasapiProxy_messageHandler: Got message "Open Device" (0x0400, lparam=00DAA8B0, wparam=0019F6E4)
AL lib: (II) GetConfigValue: Key ambi-format not found
AL lib: (II) alcOpenDevice: Created device 06030050, "OpenAL Soft on Speakers (SB Audigy)"
AL lib: (II) GetConfigValue: Key hrtf not found
AL lib: (II) UpdateDeviceParams: Pre-reset: Stereo, Float, 44100hz, 1024 update size x3
AL lib: (II) ALCwasapiProxy_messageHandler: Got message "Reset Device" (0x0401, lparam=00DAA8B0, wparam=0019F72C)
AL lib: (II) UpdateDeviceParams: Post-reset: 7.1 Surround, Float, 48000hz, 960 update size x3
AL lib: (II) GetConfigValue: Key decoder/surround71 not found
AL lib: (II) GetConfigValue: Key front-stablizer not found
AL lib: (II) aluInitRenderer: Front stablizer disabled
AL lib: (II) UpdateDeviceParams: Channel config, Dry: 8, FOA: 0, Real: 0
AL lib: (II) UpdateDeviceParams: Allocating 8 channels, 65536 bytes
AL lib: (II) UpdateDeviceParams: Max sources: 256 (255 + 1), effect slots: 64, sends: 2
AL lib: (II) GetConfigValue: Key dither not found
AL lib: (II) GetConfigValue: Key dither-depth not found
AL lib: (II) UpdateDeviceParams: Dithering disabled
AL lib: (II) GetConfigValue: Key output-limiter not found
AL lib: (II) UpdateDeviceParams: Output limiter enabled
AL lib: (II) ALCwasapiProxy_messageHandler: Got message "Start Device" (0x0402, lparam=00DAA8B0, wparam=0019F72C)
AL lib: (II) GetConfigValue: Key volume-adjust not found
AL lib: (II) alcCreateContext: Created context 00DABD00
AL lib: (II) ALCwasapiProxy_messageHandler: Got message "Stop Device" (0x0403, lparam=00DAA8B0, wparam=0019F834)
AL lib: (II) FreeContext: 00DABD00
AL lib: (II) FreeContext: Freed 0 context property objects
AL lib: (II) FreeContext: Freed 0 AuxiliaryEffectSlot property objects
AL lib: (II) FreeContext: Freed 0 voice property objects
AL lib: (II) FreeContext: Freed unapplied listener update 00DAAA10
AL lib: (II) FreeContext: Freed 0 listener property objects
AL lib: (II) FreeDevice: 06030050
AL lib: (II) ALCwasapiProxy_messageHandler: Got message "Close Device" (0x0404, lparam=00DAA8B0, wparam=0019F7EC)
AL lib: (II) GetConfigValue: Key channels not found
AL lib: (II) GetConfigValue: Key sample-type not found
AL lib: (II) GetConfigValue: Key frequency not found
AL lib: (II) GetConfigValue: Key periods not found
AL lib: (II) GetConfigValue: Key period_size not found
AL lib: (II) GetConfigValue: Key sources not found
AL lib: (II) GetConfigValue: Key slots not found
AL lib: (II) GetConfigValue: Key sends not found
AL lib: (II) ALCwasapiProxy_messageHandler: Got message "Open Device" (0x0400, lparam=00DAC930, wparam=0019F81C)
AL lib: (II) GetConfigValue: Key ambi-format not found
AL lib: (II) alcOpenDevice: Created device 060304B0, "OpenAL Soft on Speakers (SB Audigy)"
AL lib: (II) GetConfigValue: Key hrtf not found
AL lib: (II) UpdateDeviceParams: Pre-reset: Stereo, Float, 44100hz, 1024 update size x3
AL lib: (II) ALCwasapiProxy_messageHandler: Got message "Reset Device" (0x0401, lparam=00DAC930, wparam=0019F860)
AL lib: (II) UpdateDeviceParams: Post-reset: 7.1 Surround, Float, 48000hz, 960 update size x3
AL lib: (II) GetConfigValue: Key decoder/surround71 not found
AL lib: (II) GetConfigValue: Key front-stablizer not found
AL lib: (II) aluInitRenderer: Front stablizer disabled
AL lib: (II) UpdateDeviceParams: Channel config, Dry: 8, FOA: 0, Real: 0
AL lib: (II) UpdateDeviceParams: Allocating 8 channels, 65536 bytes
AL lib: (II) UpdateDeviceParams: Max sources: 256 (255 + 1), effect slots: 64, sends: 2
AL lib: (II) GetConfigValue: Key dither not found
AL lib: (II) GetConfigValue: Key dither-depth not found
AL lib: (II) UpdateDeviceParams: Dithering disabled
AL lib: (II) GetConfigValue: Key output-limiter not found
AL lib: (II) UpdateDeviceParams: Output limiter enabled
AL lib: (II) ALCwasapiProxy_messageHandler: Got message "Start Device" (0x0402, lparam=00DAC930, wparam=0019F860)
AL lib: (II) GetConfigValue: Key volume-adjust not found
AL lib: (II) alcCreateContext: Created context 00DABD00
AL lib: (II) ALCwasapiProxy_messageHandler: Got message "Stop Device" (0x0403, lparam=00DAC930, wparam=0019F9B0)
AL lib: (II) FreeContext: 00DABD00
AL lib: (II) FreeContext: Freed 0 context property objects
AL lib: (II) FreeContext: Freed 0 AuxiliaryEffectSlot property objects
AL lib: (II) FreeContext: Freed 2 voice property objects
AL lib: (II) FreeContext: Freed 2 listener property objects
AL lib: (II) FreeDevice: 060304B0
AL lib: (II) ALCwasapiProxy_messageHandler: Got message "Close Device" (0x0404, lparam=00DAC930, wparam=0019F964)
```

**Comment by Krakean** [comment] 2018-04-03 08:54
@kcat 
curious, when approximatelly you plan to release new stable version of OpenAL Soft?

**Comment by vmech** [comment] 2018-04-05 03:55
@kcat a new problem has appeared with new dll. Need to turn on resampler to convert 44.1kHz sounds to 48kHz, otherwise some high-frequency sounds are distorted. The best effect is a sinc4, but it is not perfect either.

**Comment by kcat** [comment] 2018-04-05 21:38
> a new problem has appeared with new dll. Need to turn on resampler to convert input 44.1kHz sounds to 48kHz chip processing, otherwise some high-frequency sounds are distorted. The best result is a sinc4, but it is not perfect either.

The default resampler is `linear`, which is quite fast but not very good. In the new DLL, `sinc4` was actually replaced by `cubic`, which is a bit better than `linear` but is slower. `bsinc12` (previously known as just `bsinc`) should be a bit better, and `bsinc24` should be even better.

> PS. `frequency=44100` cant help :(
```
AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80070057
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
AL lib: (II) UpdateDeviceParams: Post-reset: 7.1 Surround, Float, 48000hz, 960 update size x3
```
WASAPI/MMDevAPI doesn't allow using different sample rates, so it relies on OpenAL Soft's resampler to match input sounds to the device. Previously when OpenAL Soft was using the DirectSound backend, it could make a 44.1khz playback buffer and let DirectSound resample for output.

**Comment by KRodinn** [comment] 2018-04-07 08:52
@kcat There is one more problem.
In a stalker, there are often freezes when spawning NPCs (or when creating screenshots for example).
And at this moment all background sounds disappear.
I even found a commit with which this problem started: https://github.com/kcat/openal-soft/commit/5c859af24ea44dabbbb31631309bb08a858a523e
Is there any way to fix this?

**Comment by vmech** [comment] 2018-04-08 06:11
@KRodinn я пошёл по пути наименьшего сопротивления:
Взял исходники 1.17.2, добавил к ним коммиты kcat/openal-soft@bc386af и kcat/openal-soft@414b56e, и пересобрал x86 dll'ку.
Вроде работает, в логе порядок.

ЗЫ. Ещё бы ресемплер посвежее к ней прикрутить, и мне бы этого вполне хватило.

**Comment by KRodinn** [comment] 2018-04-08 06:41
@vmech так-то и я могу сделать, но всё равно проблема же есть, хотелось бы чтоб на последней версии поправили.

**Comment by kcat** [comment] 2018-04-08 07:41
> And at this moment all background sounds disappear.
> I even found a commit with which this problem started: 5c859af
> Is there any way to fix this?

Looking at [the source](https://github.com/OpenXRay/xray-16/blob/xd_dev/src/xrSound/SoundRender_TargetA.cpp#L96), it seems to be a bug in the engine. If there's a long enough freeze and the sources underrun, they go to an AL_STOPPED state. That update function will correctly see this and remove/refill/requeue the buffers, but doesn't restart the source (that's in the separate `else` block that didn't run this time). Because the source remains AL_STOPPED, the next update will still see all the buffers marked as processed and remove/refill/requeue them again. It keeps doing this and never actually restarts the source after an underrun.

**Comment by vmech** [comment] 2018-04-08 17:12
@kcat as far as I understand [CoC-Xray](https://github.com/revolucas/CoC-Xray/blob/a5b3e88b6093656c507ba7d2d0803f295911bafe/src/xrSound/SoundRender_TargetA.cpp#L98) and [Xray-Oxygen](https://github.com/xrOxygen/xray-oxygen/blob/bd6ed652f683b5e348db03313799c6caf3135a0f/code/engine.vc2008/xrSound/SoundRender_TargetA.cpp#L112) have an identical bug, right?

**Comment by KRodinn** [comment] 2018-04-08 17:14
@kcat Thanks, I fixed it!
@vmech да, конечно.

**Comment by ForserX** [comment] 2018-04-08 20:37
@kcat, you can push x64 release (windows) build? I'm not really friends with CMake.

**Comment by kcat** [comment] 2018-04-08 21:08
Sure, here: [soft_oal64.dll.zip](https://github.com/kcat/openal-soft/files/1887928/soft_oal64.dll.zip)

**Comment by kcat** [comment] 2018-04-09 06:36
Yeah.

**Comment by vmech** [comment] 2018-04-10 23:42
@kcat what do you think about implementing [SoX](http://sox.sourceforge.net/) into `openal-soft` for featured sound processing?

**Comment by kcat** [comment] 2018-04-11 00:40
I'd rather not rely on external libraries for effect/filter processing. Presuming no license issues, we could maybe copy and adapt code for specific effects or filters if there's something OpenAL Soft is missing or could do better with, but those should be made into individual feature/pull requests.

**Comment by vmech** [comment] 2018-04-11 02:51
@kcat I mean not external libraries, but some parts of algorithms, e.g. very fast and quality resampling from SoX.

**Comment by kcat** [comment] 2018-04-11 03:00
If SoX has faster and better quality algorithms than what OpenAL Soft currently has, and the license is compatible, it would certainly be worth considering. Feel free to make a feature request with particular algorithms (source links, preferably) if you know which would be useful.

**Comment by vmech** [comment] 2018-04-13 01:39
@kcat Can you explain to me what mean `hardware sound buffers` on screenshot? It's a similar `sources` in `alsoft.ini`? Or m.b. it's a `effect slots`? Please.
https://image.prntscr.com/image/KMFdQT0oQTi8ABOApZJDGw.png

**Closed** 2018-04-13 18:09 UTC

**Comment by donizettilorenzo** [comment] 2021-03-06 18:17
Up!

Yes, the sound dropping (tipically after a quicksave) it's and engine-related problem, still with wrap_oal it DOESN'T appear.
Any solution from the OpenAL Soft side? "Ignore" for Suspend Context DOESN'T work.

Problem is present in Lost Alpha too.
