### ISSUE TITLE
Is iOS supported? If so, how do you compile it?

### ISSUE THREAD

**Issue by jay072** [kcat/openal-soft#406] opened 2020-03-31 12:19 UTC
I've seen a few issues on this repository regarding iOS support, but it's not clear if it's officially supported, and I haven't found any instructions on how to set it up. I cannot use the native OpenAL framework anymore, since Apple has deprecated this in the latest iOS and is likely to be removed soon.

Is it possible to build for iOS, if so: how?

I've successfully used the following toolchain to setup the Xcode project
https://github.com/cristeab/ios-cmake/blob/master/toolchain/iOS.cmake

However, when building I get issues about the "native-tools" target.
```target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphoneos' platform```

```
cd /.../openal-soft/ios/native-tools && /Applications/CMake.app/Contents/bin/cmake -G Xcode /.../openal-soft/native-tools
-- The C compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- broken
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /.../openal-soft/ios/native-tools/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project CMAKE_TRY_COMPILE.xcodeproj build -target cmTC_7b571 -configuration Debug -hideShellScriptEnvironment && Command line invocation:
        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project CMAKE_TRY_COMPILE.xcodeproj build -target cmTC_7b571 -configuration Debug -hideShellScriptEnvironment
    
    User defaults from command line:
        HideShellScriptEnvironment = YES
    
    Build settings from command line:
        TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
    
    Prepare build
    note: Using legacy build system
    === BUILD TARGET cmTC_7b571 OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===
    
    Check dependencies
    target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphoneos' platform
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	Check dependencies
    (1 failure)
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
See also "/.../openal-soft/ios/native-tools/CMakeFiles/CMakeOutput.log".
See also "/.../openal-soft/ios/native-tools/CMakeFiles/CMakeError.log".
make: *** [/.../openal-soft/ios/native-tools/bin2h] Error 1
Command /bin/sh failed with exit code 2
```

**Comment by kcat** [comment] 2020-03-31 22:49
I've had other reports of that toolchain not working (see issue #335). From what was mentioned there, CMake 1.15 and newer should be able to handle iOS targets natively. Try running
```
cmake .. -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphoneos
```
from a clean build tree.

**Comment by halx99** [comment] 2020-07-20 15:19
Hi, kcat I use the command, but failed, my system is macOS-15.14, xcode11.4

> I've had other reports of that toolchain not working (see issue #335). From what was mentioned there, CMake 1.15 and newer should be able to handle iOS targets natively. Try running
> 
> ```
> cmake .. -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphoneos
> ```
> 
> from a clean build tree.

see the error output:
```
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at CMakeLists.txt:455 (MESSAGE):
  PThreads is required for non-Windows builds!


-- Configuring incomplete, errors occurred!
See also "/Users/bel/dev/openal-soft/build/CMakeFiles/CMakeOutput.log".
See also "/Users/bel/dev/openal-soft/build/CMakeFiles/CMakeError.log".
```

**Comment by kcat** [comment] 2020-07-21 15:39
What does iOS/iPhone use for threading? I guess pthreads specifically isn't needed (it's used to set real-time priority on the mixing thread, which isn't used in CoreAudio as the system controls the mixing callback thread, and setting a thread name, which is only a nicety and similarly not used for CoreAudio), but it does have to support threads (`std::thread`) in general.

**Comment by halx99** [comment] 2020-07-21 16:14
I can confirm, ios support std::thread & pthread.

**Comment by kcat** [comment] 2020-07-21 17:52
> I can confirm, ios support std::thread & pthread.

You mean it does support pthread? Then what would be needed to include `pthread.h`?

**Comment by kcat** [comment] 2020-07-21 19:35
Looking at the build log for the iOS CI PR, it looks like nothing is found. `sys/types.h`, `stdint.h`, stddef.h`, sizeof long, etc, all fail. Does something else need to be set for targeting iOS?

**Comment by halx99** [comment] 2020-07-21 23:58
just include <thread> is enough for c++

**Comment by kcat** [comment] 2020-07-22 00:11
Looking at [the build log](https://travis-ci.org/github/kcat/openal-soft/jobs/710423458), no include will work. It can't even detect the size of a long, or what command line switches work. Something more than `-DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphoneos` is apparently needed.

**Comment by halx99** [comment] 2020-07-22 01:06
Maybe, and I have try more refer from 
https://cmake.org/cmake/help/v3.17/manual/cmake-toolchains.7.html?highlight=iphoneos#cross-compiling-for-ios-tvos-or-watchos
but still doesn't work

**Comment by kcat** [comment] 2020-07-22 01:55
Does `cmake .. -GXcode -DCMAKE_SYSTEM_NAME=iOS` alone not work? What about `cmake .. -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64`?

**Comment by halx99** [comment] 2020-07-22 03:24
Yes, still doesn't work, see: https://travis-ci.com/github/simdsoft/openal-soft/jobs/363578228

**Comment by halx99** [comment] 2020-07-22 12:15
I also install latest cmake-3.18, then still doesn't works, so I think currently, for build ios device library of openal-soft, we should use a custom ios.toolchain.cmake, just see my PR

**Comment by halx99** [comment] 2020-08-05 13:18
Since travis ios PR was merged, this issue could be close

**Closed** 2020-08-05 13:23 UTC

**Comment by liwenjun97** [comment] 2021-01-05 01:59
same problem
