### ISSUE TITLE
assert_fail gain > 0.00001f BiquadFilter_setParams

### ISSUE THREAD

**Issue by LordOfDragons** [kcat/openal-soft#339] opened 2019-09-05 20:57 UTC
This suddenly shows up with 1.19.1 version of OpenAl. Causes application to crash if it happens since it happens inside the OpenAL thread. Attached the backtrace.

**Comment by LordOfDragons** [comment] 2019-09-05 20:58
Looks like I can not attach anything:
`*** Program received signal SIGABRT (Aborted) ***(gdb) 54bt
#0 __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1 0x00007f189687b535 in __GI_abort () at abort.c:79
#2 0x00007f189687b40f in __assert_fail_base (fmt=0x7f1896a09588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7f188e9ed73a "gain > 0.00001f", file=0x7f188e9ed6e0 "/home/roland/progs/dragengine/extern/openal/build/openal-soft-1.19.1/Alc/filters/filter.c", line=25, function=<optimized out>) at assert.c:92
#3 0x00007f189688b012 in __GI___assert_fail (assertion=assertion@entry=0x7f188e9ed73a "gain > 0.00001f", file=file@entry=0x7f188e9ed6e0 "/home/roland/progs/dragengine/extern/openal/build/openal-soft-1.19.1/Alc/filters/filter.c", line=line@entry=25, function=function@entry=0x7f188e9ed770 <__PRETTY_FUNCTION__.6398> "BiquadFilter_setParams") at assert.c:101
#4 0x00007f188e985710 in BiquadFilter_setParams (filter=filter@entry=0x7f1880244740, type=type@entry=BiquadType_HighShelf, gain=gain@entry=9.78387834e-06, f0norm=f0norm@entry=0.113378681, rcpQ=<optimized out>) at /home/roland/progs/dragengine/extern/openal/build/openal-soft-1.19.1/Alc/filters/filter.c:70
#5 0x00007f188e983d9a in CalcT60DampingCoeffs (filter=<optimized out>, hf0norm=0.113378681, lf0norm=0.00566893443, hfDecayTime=0.100000001, mfDecayTime=<optimized out>, lfDecayTime=0.524377525, length=<optimized out>) at /home/roland/progs/dragengine/extern/openal/build/openal-soft-1.19.1/Alc/filters/defs.h:50
#6 UpdateLateLines (Late=0x7f1880244640, frequency=<optimized out>, hf0norm=0.113378681, lf0norm=0.00566893443, hfDecayTime=0.100000001, mfDecayTime=<optimized out>, lfDecayTime=0.524377525, diffusion=1, density=<optimized out>) at /home/roland/progs/dragengine/extern/openal/build/openal-soft-1.19.1/Alc/effects/reverb.c:859
#7 ReverbState_update (Slot=0x7f188023c080, props=<optimized out>, Context=<optimized out>, State=0x7f1880244210) at /home/roland/progs/dragengine/extern/openal/build/openal-soft-1.19.1/Alc/effects/reverb.c:1005
#8 ReverbState_ALeffectState_update (obj=0x7f1880244210, a=<optimized out>, b=0x7f188023c080, c=<optimized out>) at /home/roland/progs/dragengine/extern/openal/build/openal-soft-1.19.1/Alc/effects/reverb.c:340
#9 0x00007f188e979a4e in CalcEffectSlotParams (slot=0x7f188023c080, context=context@entry=0x7f1880012800, force=force@entry=false) at /home/roland/progs/dragengine/extern/openal/build/openal-soft-1.19.1/Alc/ALu.c:505
#10 0x00007f188e97ddbb in ProcessParamUpdates (slots=0x7f1880239130, ctx=0x7f1880012800) at /home/roland/progs/dragengine/extern/openal/build/openal-soft-1.19.1/Alc/ALu.c:1552
#11 aluMixData (device=device@entry=0x7f1880012f30, OutBuffer=OutBuffer@entry=0x7f1868000e00, NumSamples=NumSamples@entry=1024) at /home/roland/progs/dragengine/extern/openal/build/openal-soft-1.19.1/Alc/ALu.c:1773
#12 0x00007f188e995411 in ALCpulsePlayback_mixerProc (ptr=ptr@entry=0x7f1880008990) at /home/roland/progs/dragengine/extern/openal/build/openal-soft-1.19.1/Alc/backends/pulseaudio.c:875
#13 0x00007f188e999f97 in althrd_starter (arg=<optimized out>) at /home/roland/progs/dragengine/extern/openal/build/openal-soft-1.19.1/common/threads.c:487
#14 0x00007f1896838182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#15 0x00007f1896973b1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
54^done`

**Comment by kcat** [comment] 2019-09-05 21:29
This should be fixed in current master, which makes sure the proper limit is applied.

**Comment by LordOfDragons** [comment] 2019-09-06 15:50
Any ETA for an official release? Right now I apply a patch file for this.

**Comment by kcat** [comment] 2019-09-06 21:54
I would like to have one within the month, although given the change to C++ and the amount of restructuring with that change, it's going to need a lot of testing which might need a bit more time depending on what turns up. But I can hope within 2 or 3 weeks or so.

**Comment by kcat** [comment] 2019-12-12 23:03
1.20 was released which should deal with this. Can you check to make sure the problem is fixed?

**Closed** 2020-01-18 00:27 UTC
