### ISSUE TITLE
about bsinc_inc.h

### ISSUE THREAD

**Issue by sdragonx** [kcat/openal-soft#250] opened 2018-11-28 06:17 UTC
i using ndk-build compile libopengl.so, but result error:
jni/openal/Alc/ALu.c:47:10: fatal error: 'bsinc_inc.h' file not found

i use the cmake whith ndk/build/cmake/android.toolchain.cmake, but can not compiled.
my platform is win10 64bit.

**Comment by kcat** [comment] 2018-11-28 06:54
How did you run cmake, and what's the full output? What's your main/native compiler? Can you give the build output?

**Comment by sdragonx** [comment] 2018-11-28 07:34
CMake Error at CMakeLists.txt:25 (INCLUDE):
  INCLUDE could not find load file:

    CheckSharedFunctionExists


CMake Error at CMakeLists.txt:34 (include):
  include could not find load file:

    CheckFileOffsetBits


CMake Error at CMakeLists.txt:149 (CHECK_FILE_OFFSET_BITS):
  Unknown CMake command "CHECK_FILE_OFFSET_BITS".


Configuring incomplete, errors occurred!
See also "D:/users/sdragonx/desktop/lib/openal-soft-1.19.1/jni/openal/CMakeFiles/CMakeOutput.log".
See also "D:/users/sdragonx/desktop/lib/openal-soft-1.19.1/jni/openal/CMakeFiles/CMakeError.log".

**Comment by sdragonx** [comment] 2018-11-28 07:42
current version softal, using cmake compile the code. but cmake using native compiler to be check SIZEOF_LONG, SIZEOF_LONG_LONG.
in the directory "openal\CMakeFiles\CheckTypeSize", cmake compiled "SIZEOF_LONG.bin"，and "SIZEOF_LONG_LONG.bin", but windows platform can not run the bincode.
why use such a design ?
simple style facilitates cross-platform compilation.

**Comment by kcat** [comment] 2018-11-28 21:02
Odd that it can't find those files since they're in `${OpenAL_SOURCE_DIR}/cmake`, which the module path is set to. Can you provide the full output from a fresh build directory?

> current version softal, using cmake compile the code. but cmake using native compiler to be check SIZEOF_LONG, SIZEOF_LONG_LONG.

What's the command you used to run cmake? It shouldn't use the native compiler for those, it should use the same compiler it would build the library with.

> in the directory "openal\CMakeFiles\CheckTypeSize", cmake compiled "SIZEOF_LONG.bin"，and "SIZEOF_LONG_LONG.bin", but windows platform can not run the bincode.

Those files are actually created by cmake's `CHECK_TYPE_SIZE()` function. It generates a source file and compiles it into an executable, then reads the strings in the executable to find the size of the specified type. It doesn't actually run the executable. It's a convoluted method cmake uses, I agree, but there's not many better ways to figure out the size of a type a given compiler uses.

**Comment by sdragonx** [comment] 2018-11-29 08:35
I need so library files for Android platform. Where there is a download address, I can not compile it.
Android platform only opensl, no al support.

**Comment by kcat** [comment] 2018-12-02 03:07
Is it possible to provide binaries like that? Couldn't there be a problem with using a prebuilt library with a different compiler version? Especially now that it uses libc++, the library and your app would need to be built against the same version. It would probably also depend on your target CPU.

If you can provide the cmake command you used, and the full output from a fresh build directory, I can help you figure out what's wrong.

**Comment by sdragonx** [comment] 2018-12-05 04:46
.bat file:
set TOOLCHAIN="%NDK_ROOT%\build\cmake\android.toolchain.cmake"
E:\MyStudio\cmake\bin\cmake -DCMAKE_TOOLCHAIN_FILE=%TOOLCHAIN% -DANDROID_NDK=%NDK_ROOT% -DCMAKE_BUILD_TYPE=Release
E:\MyStudio\cmake\bin\cmake --build "D:\Users\sdragonx\Desktop\lib\openal-soft-1.19.1\jni\openal"
pause
-----------------------------------------------------------------------------------------
output message:

CMake Warning at E:/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake:63 (message):
  Using custom NDK path (ANDROID_NDK is set): E:\Android\SDK\ndk-bundle
Call Stack (most recent call first):
  CMakeFiles/3.13.0/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:5 (PROJECT)


CMake Error at CMakeLists.txt:25 (INCLUDE):
  INCLUDE could not find load file:

    CheckSharedFunctionExists


CMake Error at CMakeLists.txt:34 (include):
  include could not find load file:

    CheckFileOffsetBits


CMake Error at CMakeLists.txt:149 (CHECK_FILE_OFFSET_BITS):
  Unknown CMake command "CHECK_FILE_OFFSET_BITS".


-- Configuring incomplete, errors occurred!

**Comment by sdragonx** [comment] 2018-12-05 04:52
What does bsinc_inc.h have? Why not use # define ...

**Comment by kcat** [comment] 2019-01-03 07:33
> What does bsinc_inc.h have?

It has the tables for the bsinc12 and bsinc24 resamplers. Since they're not trivial to calculate, the bsincgen utility generates the headers. And to ensure the headers don't get out of sync (i.e. forgetting to rebuild or commit the header after changing the utility), it's done during the build. The bin2h utility is similar, generating the headers for the built-in HRTF data sets from the default mhr files.

> Same issue here. Cross compile 1.19.1 using Android NDK r19 Beta 2 on macOS Mojave 10.14.2, cmake 3.13.2 via homebrew.

Do you have the `CC` environment variable set to a non-native compiler? It's unnecessary to change `CC`, `CXX`, or `LD` (or the related `*FLAGS`) env vars for cross-compiling with CMake; it's insufficient for cmake scripts to detect the proper target, and will instead inhibit sub-builds that need the native compiler like this. The `CMAKE_TOOLCHAIN_FILE` handles setting up the compiler executable and needed compiler flags for cross-compiling, and sets the proper target system identification (so the scripts will know it's building for Android, in this case).

**Comment by pixelblender** [comment] 2019-01-03 08:53
> Do you have the `CC` environment variable set to a non-native compiler?

Apparently this what fails the build. I set `CC` to `aarch64-linux-android21-clang` / `armv7a-linux-androideabi16-clang`. Without it the code compiles successfully. Although I haven't test it further with actual Android devices.

Thanks @kcat ! Keep up the good work! looking forward to the day openal-soft switch to MIT/no longer LGPL ;)

**Comment by qwertychouskie** [comment] 2019-01-03 19:32
What's wrong with LGPL?  LGPL libraries can be linked to proprietary programs AFAIK.

**Comment by kcat** [comment] 2019-01-04 03:45
Some platforms don't allow LGPL code because of restrictions on being able to replace the library. A game that's run directly from a CD/DVD/Blu-Ray, for example, wouldn't be able to replace libopenal.so/dll with an alternative version. Some platforms don't support or allow dynamic linking, so to adhere to the LGPL they'd have to provide the object files and allow you to relink the executable, which can be impractical.

OpenAL Soft is currently under the LGPL 2, so it at least lacks the anti-TiVo-ization clause AFAIK ("TiVo-ization" basically being where you can physically replace the code, but DRM prevents the replaced/unsigned code from being used by the system). But for systems where you can't even replace the code, the LGPL is still a problem.

**Comment by GekkieHenkie** [comment] 2019-05-03 14:36
The generation of the bsincgen and bin2h executables stays problematic, at least when trying to build for Android cross compiled on Windows.

But I've fixed it, removing the -G ${CMAKE_GENERATOR} in the add_external_command() call. The Android toolchain implicitly provides the command with the Ninja generator, but if you don't have Ninja outside the NDK, it will fail. Removing the -G argument fixed it, and defaults to the native generator creating executables.
As such, I suggest removing the -G argument from the command for creating the native-tools binaries.

**Comment by kcat** [comment] 2019-05-03 18:25
The problem is, CMake's default generator may be unsuitable on a given system. For example, if it defaults to VS2019 but a user has VS2017 installed. Thew only generator it can know works is the one it's using.

**Comment by smallcoderofme** [comment] 2020-07-29 08:44
> The problem is, CMake's default generator may be unsuitable on a given system. For example, if it defaults to VS2019 but a user has VS2017 installed. Thew only generator it can know works is the one it's using.

My English is not very good. What is the ultimate solution to this problem? My English is not very good. What is the ultimate solution to this problem? My OS is win 7, vs 2017

**Comment by smallcoderofme** [comment] 2020-07-29 08:45
> The problem is, CMake's default generator may be unsuitable on a given system. For example, if it defaults to VS2019 but a user has VS2017 installed. Thew only generator it can know works is the one it's using.

My English is not very good.  What is the ultimate solution to this problem? My pc OS is win 7, vs 2017

**Comment by kcat** [comment] 2020-07-29 17:43
Current master shouldn't have problems with bsinc_inc.h since it doesn't use native sub-builds anymore. Are you seeing a problem with the latest code?

**Comment by smallcoderofme** [comment] 2020-07-30 00:47
Yes. Mine is already the latest master branch.

  log: 

--  Build Shared Library: ON
--  Build Static Library: ON
--  Build Static Library with Position Independent Code: OFF

CMake Error at openal-soft/CMakeLists.txt:25 (INCLUDE):
  INCLUDE could not find load file:

    CheckSharedFunctionExists

CMake Error at openal-soft/CMakeLists.txt:34 (include):
  include could not find load file:

    CheckFileOffsetBits

CMake Error at openal-soft/CMakeLists.txt:149 (CHECK_FILE_OFFSET_BITS):
  Unknown CMake command "CHECK_FILE_OFFSET_BITS".

-- Configuring incomplete, errors occurred!
See also "D:/android/heaps-android/build/CMakeFiles/CMakeOutput.log".
See also "D:/android/heaps-android/build/CMakeFiles/CMakeError.log".

**Comment by kcat** [comment] 2021-03-10 09:46
Closing as handled, `bsinc_inc.h` is no longer generated at build time with a custom utility.

**Closed by kcat** 2021-03-10 09:46 UTC

**Comment by sdragonx** [comment] 2021-05-09 17:03
It seems that I am not the only one who has encountered problems. I seem to have solved them, but I forget how to solve them. Sometimes programming "tricks" can be troublesome.

**Comment by sdragonx** [comment] 2021-05-09 17:18
[bsinc_inc.zip](https://github.com/kcat/openal-soft/files/6448077/bsinc_inc.zip)
