### ISSUE TITLE
1.21.0: build fails

### ISSUE THREAD

**Issue by kloczek** [kcat/openal-soft#518] opened 2021-01-20 10:44 UTC
```
[tkloczko@barrel x86_64-redhat-linux-gnu]$ make
/usr/bin/cmake -S/home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0 -B/home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu/CMakeFiles /home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu'
make  -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/depend
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu'
cd /home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0 /home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0 /home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu /home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu /home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu/CMakeFiles/common.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu'
make  -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/build
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu'
[  1%] Building CXX object CMakeFiles/common.dir/common/almalloc.cpp.o
/usr/bin/g++ -DRESTRICT=__restrict -I/home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu -I/home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/include -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -fdata-sections -ffunction-sections -fno-rtti -O2 -g -D_DEBUG -fPIC -Winline -Wunused -Wall -Wextra -Wshadow -Wconversion -Wcast-align -Wpedantic -Wold-style-cast -Wnon-virtual-dtor -Woverloaded-virtual -fno-math-errno -fvisibility=hidden -pthread -std=gnu++14 -o CMakeFiles/common.dir/common/almalloc.cpp.o -c /home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/common/almalloc.cpp
/home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/common/almalloc.cpp: In function ‘void* al_malloc(size_t, size_t)’:
/home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/common/almalloc.cpp:23:17: error: ‘aligned_alloc’ is not a member of ‘std’; did you mean ‘aligned_union’?
   23 |     return std::aligned_alloc(alignment, size);
      |                 ^~~~~~~~~~~~~
      |                 aligned_union
make[2]: *** [CMakeFiles/common.dir/build.make:124: CMakeFiles/common.dir/common/almalloc.cpp.o] Error 1
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu'
make[1]: *** [CMakeFiles/Makefile2:142: CMakeFiles/common.dir/all] Error 2
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.21.0/x86_64-redhat-linux-gnu'
make: *** [Makefile:152: all] Error 2
```

**Comment by kloczek** [comment] 2021-01-20 10:46
Just retested 1.20.0 still is ok in my build env.

**Comment by kloczek** [comment] 2021-01-20 10:51
cmake configuration:
```
[tkloczko@barrel x86_64-redhat-linux-gnu]$ cmake -L
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error: The source directory "/home/tkloczko/rpmbuild/BUILD/openal-soft-openal-soft-1.20.0/x86_64-redhat-linux-gnu" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
ALSOFT_AMBDEC_PRESETS:BOOL=ON
ALSOFT_BACKEND_ALSA:BOOL=ON
ALSOFT_BACKEND_OSS:BOOL=OFF
ALSOFT_BACKEND_PORTAUDIO:BOOL=OFF
ALSOFT_BACKEND_PULSEAUDIO:BOOL=OFF
ALSOFT_BACKEND_WAVE:BOOL=ON
ALSOFT_CONFIG:BOOL=ON
ALSOFT_CPUEXT_SSE:BOOL=ON
ALSOFT_CPUEXT_SSE2:BOOL=ON
ALSOFT_CPUEXT_SSE3:BOOL=ON
ALSOFT_CPUEXT_SSE4_1:BOOL=ON
ALSOFT_DLOPEN:BOOL=ON
ALSOFT_EMBED_HRTF_DATA:BOOL=ON
ALSOFT_EXAMPLES:BOOL=ON
ALSOFT_HRTF_DEFS:BOOL=ON
ALSOFT_INSTALL:BOOL=ON
ALSOFT_NATIVE_TOOLS_PATH:STRING=
ALSOFT_NO_CONFIG_UTIL:BOOL=OFF
ALSOFT_NO_QT5:BOOL=OFF
ALSOFT_REQUIRE_ALSA:BOOL=ON
ALSOFT_REQUIRE_COREAUDIO:BOOL=OFF
ALSOFT_REQUIRE_DSOUND:BOOL=OFF
ALSOFT_REQUIRE_JACK:BOOL=OFF
ALSOFT_REQUIRE_NEON:BOOL=OFF
ALSOFT_REQUIRE_OPENSL:BOOL=OFF
ALSOFT_REQUIRE_OSS:BOOL=OFF
ALSOFT_REQUIRE_PORTAUDIO:BOOL=OFF
ALSOFT_REQUIRE_PULSEAUDIO:BOOL=OFF
ALSOFT_REQUIRE_QSA:BOOL=OFF
ALSOFT_REQUIRE_SDL2:BOOL=OFF
ALSOFT_REQUIRE_SNDIO:BOOL=OFF
ALSOFT_REQUIRE_SOLARIS:BOOL=OFF
ALSOFT_REQUIRE_SSE:BOOL=OFF
ALSOFT_REQUIRE_SSE2:BOOL=OFF
ALSOFT_REQUIRE_SSE3:BOOL=OFF
ALSOFT_REQUIRE_SSE4_1:BOOL=OFF
ALSOFT_REQUIRE_WASAPI:BOOL=OFF
ALSOFT_REQUIRE_WINMM:BOOL=OFF
ALSOFT_STATIC_LIBGCC:BOOL=OFF
ALSOFT_STATIC_STDCXX:BOOL=OFF
ALSOFT_TESTS:BOOL=ON
ALSOFT_UTILS:BOOL=ON
ALSOFT_WERROR:BOOL=OFF
CMAKE_BUILD_TYPE:STRING=RelWithDebInfo
CMAKE_DEBUG_POSTFIX:STRING=
CMAKE_INSTALL_PREFIX:PATH=/usr
COREAUDIO_FRAMEWORK:FILEPATH=COREAUDIO_FRAMEWORK-NOTFOUND
MYSOFA_M_LIBRARY:FILEPATH=/usr/lib64/libm.so
Qt5Core_DIR:PATH=/usr/lib64/cmake/Qt5Core
Qt5Gui_DIR:PATH=/usr/lib64/cmake/Qt5Gui
Qt5Widgets_DIR:PATH=/usr/lib64/cmake/Qt5Widgets
SDL2MAIN_LIBRARY:FILEPATH=SDL2MAIN_LIBRARY-NOTFOUND
SDL2_CORE_LIBRARY:FILEPATH=SDL2_CORE_LIBRARY-NOTFOUND
SDL2_INCLUDE_DIR:PATH=SDL2_INCLUDE_DIR-NOTFOUND
```
Looks like despite `ALSOFT_TESTS:BOOL=ON` there is no any test suite which is possible to execute.
Q: is that part finished?

**Comment by kcat** [comment] 2021-01-20 11:27
`ALSOFT_TESTS` isn't used anymore. It's functionality has been moved to `ALSOFT_EXAMPLES`.

As for the error, that would happen if cmake finds `std::aligned_alloc` (and sets `HAVE_STD_ALIGNED_ALLOC`), but the compiler can no longer find it when compiling `almalloc.cpp`. That function was added in C++17, though OpenAL Soft only uses C++14 normally.  Does it get found by CMake with a clean cache? Is there anything peculiar about your setup that could cause configuration behave oddly? What compiler+version are you using?

**Comment by kloczek** [comment] 2021-01-20 11:38
To automated build of my package I'm usimg github autogenerated tar ball from git tag https://github.com/kcat/openal-soft/archive/openal-soft-1.21.0.tar.gz so by definition it cannot be anythiong related to the  cmake cache.
I'm using gcc 11.0.1 from fedora rawhide so I think that you need to add compiler flag to lower c++ standard (IIRC in 11.0.1 it was elevated to default C++20 or adapt code to that standard).

BTW: would you consuder chage taggiong conbvention from `openal-soft-<version>` to just `<version>`?
Gitlab/githug automatically adds to the tagged tar ball git repo name so https://github.com/kcat/openal-soft/archive/openal-soft-1.21.0.tar.gz has inside base directory `openal-soft-openal-soft-1.21.0/`

**Comment by kloczek** [comment] 2021-01-20 12:12
> `ALSOFT_TESTS` isn't used anymore. It's functionality has been moved to `ALSOFT_EXAMPLES`.
```
OPTION(ALSOFT_EXAMPLES  "Build and install example programs"  ON)
OPTION(ALSOFT_TESTS     "Build and install test programs"     ON)
```
Description says that it is about **installing** some suff .. not provide in-build-tree test suite :P

**Comment by kcat** [comment] 2021-01-20 12:46
> To automated build of my package I'm usimg github autogenerated tar ball from git tag https://github.com/kcat/openal-soft/archive/openal-soft-1.21.0.tar.gz so by definition it cannot be anythiong related to the cmake cache.

The cache may be left over from previous builds. Can you paste the output of a fresh configure+build?

> I'm using gcc 11.0.1 from fedora rawhide so I think that you need to add compiler flag to lower c++ standard (IIRC in 11.0.1 it was elevated to default C++20 or adapt code to that standard).

It sets the desired standard with cmake:
https://github.com/kcat/openal-soft/blob/e1e08092/CMakeLists.txt#L153

Unless CMake isn't applying it for the test, it's using C++14.

> Description says that it is about **installing** some suff .. not provide in-build-tree test suite :P

Yes, "building and installing" some test apps. However those were merged with the examples, so that option doesn't exist anymore in 1.21.0.

**Comment by kloczek** [comment] 2021-01-22 14:24
> The cache may be left over from previous builds. Can you paste the output of a fresh configure+build?

As I wrote I'm buiklding on valnilla builsd env ehere there is no any bits from any other biuilds. Whole build env instyalled from scratch to build single package.

Just tested and adding `-std=c++14` to $CXXFLAGS fixes build issue.

Nevertheless looks like at the moment soes not provide test suite which could be executed in build tree (there is no support for `test` targer in gebeated makefiles).

**Comment by kcat** [comment] 2021-01-22 17:02
Seems to be a CMake bug: https://gitlab.kitware.com/cmake/cmake/-/issues/15361 (originally at https://cmake.org/Bug/view.php?id=15361). `check_cxx_source_compiles` and various other cmake methods will use the compiler default language version, but `CMAKE_CXX_STANDARD` gets applied when building, resulting in the check using C++17 on newer compilers but C++14 when actually building the lib.

Commit f576a353638236775ecb4f4e8ba93cb1716fbe2d should fix it.

**Comment by past-due** [comment] 2021-01-29 21:07
@kcat Do you possibly have a rough ETA for when 1.21.1 might be published? (I'm trying to update the vcpkg port, and am trying to avoid cherry-picking a lot of compilation fixes since 1.21.0. If 1.21.1 might be coming soon-ish, that would fit the bill.)

(Thank you for all of your work on a wonderful library! 🥳)

**Comment by kcat** [comment] 2021-01-30 06:38
I could probably do a release in about a week or so. There's been a few notable bug fixes, I'd just want to check through and ensure there haven't been any regressions hiding somewhere.

**Comment by kcat** [comment] 2021-02-04 20:47
1.21.1 is now released: https://github.com/kcat/openal-soft/releases/tag/1.21.1

**Closed by kcat** 2021-02-04 20:47 UTC

**Comment by past-due** [comment] 2021-02-04 22:32
Thank you, @kcat! I've submitted a PR to update vcpkg's port: https://github.com/microsoft/vcpkg/pull/15945

**Comment by kloczek** [comment] 2021-02-05 03:22
Just tested new version and everything is OK now.
Thx :) 

Kind of question: seems like current cmake support has nothing hooked under `test` target. Is there any test suite? (cannot find anything). In my build procedures I'm trying to use any test suites as kind of self confirmation that some basic functionalities implemented in the software are OK and I think that using those test suites is very important part of the long term software maintenance.

**Comment by kcat** [comment] 2021-02-05 09:52
There isn't currently. Most of the problems I run into aren't the kind that can be easily checked with automated testing, as it tends to depend on system-specific configurations or behavior, or depends on perception (e.g. clicks and pops being aberrant noise on the signal, it's not easily testable by analyzing the rendered waveform since what matters is what the user hears). But where issues continually slip through that can be tested, having an automated test suite is the plan.

**Comment by kloczek** [comment] 2021-02-05 11:56
OK.
What about add for now empty cmake placeholder with `BUILD_TEST={ON|OFF}`? :P
Just to not fail on `make test` when `BUILD_TEST=ON` ..
As I'm reviewing now my openal-soft package build procedure it would be good to solidyfy general build anbd testing procedure for longer time until some bells will be touched :)

**Comment by kcat** [comment] 2021-02-05 20:41
I could make an `ALSOFT_BUILD_TEST` option (prepended with `ALSOFT_` to avoid conflicts when included as a sub-project). Though I'm not sure how to go about making cmake create a `test` target for make that does nothing and succeeds. I've noticed there is a CTest module to do testing with CMake, perhaps I should look into that.
