### ISSUE TITLE
OpenAL Software Silent/Freezing

### ISSUE THREAD

**Issue by reteo** [kcat/openal-soft#34] opened 2016-03-27 19:40 UTC
Following an update of my system, I discovered that all applications making use of OpenAL are silent while PulseAudio is running, and when I close them, they freeze, requiring a forceful putdown.  Blender in particular seems to be having problems with playback when "A/V Sync" is enabled. 

When the applications are running, they do make a connection to PulseAudio, as the name of the program appears in the "pavucontrol" main window.  However, there is apparently no signal being received by Pulse, as the volume meter under the program's volume bar is not showing any signal.

The upgrade in question was an upgrade to Linux Kernel version 4.2.0; I lost the kernel I previously had, as I had performed a total nuke-and-pave, assuming that the system, having been updated a lot, might just be getting fragile in its old age.

I am unable to find any logs indicating the source of the problem.  I was able to get a [backtrace](https://github.com/kcat/openal-soft/files/191075/Backtrace.txt) from the issue with Blender; this backtrace was taken following the attempt to close the program, when it froze.

I honestly don't know if the problem is in OpenAL, PulseAudio, or the kernel's ALSA drivers, but since the issue seems to only occur with programs using OpenAL, I figured this would be the best place to start.

I am currently using OpenAL-Soft 1.17.2, PulseAudio 7.0, and Kernel 4.2.0 on a fresh Lubuntu 15.10 (Wily) system.  When the issue started, I was using Ubuntu's defaults of PulseAudio 6.0 and OpenAL-Soft 1.16.0

**Comment by kcat** [comment] 2016-03-27 20:02
Hi.

That backtrace seems to be for OpenAL Soft 1.16. That version is known to have issues like this when the PulseAudio device is suspended, as it won't play OpenAL Soft's audio stream and OpenAL Soft erroneously waits for the device to wake up before it'll close the device (this latter problem being fixed in 1.17).

I'd double-check that 1.17.2 is installed properly, and that PulseAudio is working properly.

**Comment by reteo** [comment] 2016-03-27 20:29
Well, that's the thing:  each functions correctly by itself; YouTube and VLC (using the PulseAudio module), can be heard just fine through PulseAudio.  At the same time, when I completely uninstall PulseAudio (to guarantee it won't self-relaunch), I can hear OpenAL programs just fine.  So I can verify that both systems work just fine independently.

The problem seems to come to a head when they try to work together.

Now, I went through the steps with Blender, to find out that, indeed, with 1.17.2, it would close properly.  However, the VSE playback would still cycle through the same frame (the key issue with Blender/OpenAL) with A/V Sync turned on (only on OpenAL w/Pulse, Jack would work fine, OpenAL with ALSA would work fine).

I also attempted to start a game that uses OpenAL ("X Rebirth," downloaded from GOG), and found that it still has the "lock-on-close" problem.  It is with this program that I was able to get an updated 
[backtrace](https://github.com/kcat/openal-soft/files/191099/X_Rebirth_Backtrace.txt).  I hope this helps.

**Comment by kcat** [comment] 2016-03-27 20:49
> I also attempted to start a game that uses OpenAL ("X Rebirth," downloaded from GOG), and found that it still has the "lock-on-close" problem. It is with this program that I was able to get an updated
backtrace. I hope this helps.

Unfortunately that backtrace seems to be from 1.16 as well. The game seems to be using its own build of OpenAL Soft which also sees the PulseAudio device as suspended for some reason.

Something you can try with these apps still causing problems is setting the environment variables, ```ALSOFT_LOGLEVEL=3``` and ```ALSOFT_LOGFILE=/path/to/log.txt```. That should make OpenAL Soft write a full trace log to the named log file, which can hopefully shed light on the problem.

**Comment by reteo** [comment] 2016-03-27 21:06
To make sure I'm reporting on the correct version of the library, I removed 'libopenal.so.1' file from the game's private library stash; it is now using the systemwide library for the game, and like Blender, it is closing down correctly.  However, there is still no sound from the game.

I've got logfiles from both programs, though, now that I know how to get them.

* [Blender](https://github.com/kcat/openal-soft/files/191119/openal-soft-log.txt)
* [X Rebirth](https://github.com/kcat/openal-soft/files/191126/openal-soft-log.txt)

**Comment by kcat** [comment] 2016-03-27 22:12
Hmm, this is odd. For some reason, the PulseAudio stream is getting a prebuf setting of 40560 bytes, even though OpenAL Soft sets it to 0 for manual starting control. This is likely interfering with the playback stream's ability to start, since the buffering metrics won't fill it that much (the default buffer size request is 4K sample frames, or 32KB for stereo float32, which it tries to maintain even if PulseAudio creates a larger buffer, otherwise latency could get out of control) and the prebuf prevents it from being manually started.

PulseAudio's documentation doesn't mention that this value can be forced to something else by the server, ignoring an app's request for manual starting control. Does Lubuntu apply any of its own patches to OpenAL Soft? If not, I may need to ask the PulseAudio devs about this.

**Comment by reteo** [comment] 2016-03-27 22:30
The OpenAL Soft was manually downloaded from [here](https://packages.debian.org/source/sid/openal-soft), as the most recent ubuntu-specific version of the library is 1.16.0.

**Comment by reteo** [comment] 2016-03-30 00:54
I just finished downgrading my kernel back from 4.2 to 3.16; the issue is still happening, so the kernel update must have just been a coincidence.

**Comment by kcat** [comment] 2016-03-31 23:30
Sorry for the lack of responses. This has me pretty stumped as no one in #pulseaudio seems to know why this would happen either, and since I can't reproduce it myself I can't really help them narrow it down. I'll continue to poke around at it and try to see what's going on, but for now there's a couple things you can try to workaround the problem.

First is to increase the number of periods OpenAL Soft will use to 5. In the alsoft-config utility (if that is installed), simply increase the Period Count slider to 5. Or create/edit ```~/.alsoftrc``` and add the lines:
```
[general]
periods = 5
```
Alternatively, Git head now includes a built-in workaround. OpenAL Soft will increase its internal buffer size to ensure prebuf is reached for playback to start.

In both cases latency will increase a bit, but that's unavoidable as long as PulseAudio is requiring that much audio for playback to start.

**Comment by reteo** [comment] 2016-04-01 09:38
Hmmm... you can't reproduce it?  That suggests there is a setting or configuration problem on my end.  If you have anything you want me to try, let me know; worse comes to worst, it will be an extra couple bullets for the documentation.

**Comment by reteo** [comment] 2016-04-01 20:44
If it helps, there's more information available in the Ubuntu Launchpad [here](https://bugs.launchpad.net/ubuntu/+source/openal-soft/+bug/1562208).

**Comment by reteo** [comment] 2016-04-02 00:45
By the way, the period setting did work, and as you said, it does introduce some slight latency.  Not enough to make the game unplayable, but slightly disturbing.  Hopefully the root of the issue can be found.

**Comment by reteo** [comment] 2016-04-02 13:03
Okay, it looks like the problem was the buffer in Pulseaudio; according to the guy at launchpad, the default buffer fragment size is 25ms, but apparently, I needed a multiple of 10 to work with a 44100 KHz interface.  The problem was fixed by editing the following line in /etc/pulse/daemon.conf:

```
default-fragment-size-msec = 10
```

Now I just need to know *why* it worked. :-/

**Comment by kcat** [comment] 2016-04-02 13:52
Yeah, that's really weird. I'd expect the fragment size in ms to be converted to the nearest supported size in bytes or samples, and work with it. Does this change the
```
AL lib: (II) ALCpulsePlayback_bufferAttrCallback: minreq=5288, tlength=45840, prebuf=40560
```
line from the OpenAL Soft log at all?

**Comment by reteo** [comment] 2016-04-02 17:36
Well, [here's](https://github.com/kcat/openal-soft/files/200933/openal-soft.txt) the updated log for X Rebirth, and [here's](https://github.com/kcat/openal-soft/files/200935/openal-soft-2.txt) the updated log for Blender.  In both cases, the prebuf is now '19408'.

As a side note, both of these logs were made using version 1.16 of openal.

**Comment by kcat** [comment] 2016-04-02 23:59
> As for translating it to bytes or samples, wouldn't that affect PulseAudio's flexibility in terms of interface sample rates and/or dynamic range?

It ultimately has to be converted to bytes eventually regardless, since the fragment size, fragment count, and other related properties determines the amount of sample memory the DAC loops over, which may be limited, while the fragment count determines how often hardware interrupts are generated as the buffer plays back (which needs to be a clean divisor, so it interrupts at the same points in the buffer on each loop).

Since you reduced the fragment size/time from 25 to 10 while leaving the fragment count at 4 (pulse's default), it changed the hardware buffer from ~100ms to ~40ms, which could account for the general reduction of things. Still doesn't explain why prebuf is being changed, but at least it's now less than OpenAL Soft's buffer size request so it has no issue starting playback

**Comment by reteo** [comment] 2016-04-03 01:38
Fair enough.  Hopefully, this can serve as a decent workaround for others having similar issues; instead of adding to alsoft's buffer, we simply reduce the Pulse buffer.  Solves the problem without introducing latency.

**Comment by kcat** [comment] 2019-04-17 05:34
Closing as having been dealt with. The freeze-on-close for a suspended Pulse stream was fixed long ago, and OpenAL Soft will also account for any non-0 prebuf it gets back to ensure playback starts correctly.

**Closed by kcat** 2019-04-17 05:34 UTC
