### ISSUE TITLE
about compile 1.22 error 

### ISSUE THREAD

**Issue by xuandu** [kcat/openal-soft#743] opened 2022-07-25 06:39 UTC
I encountered the following problems when compiling 1.22, using cmake3.5.1;

--------------------------------------------------------------------------------------------------------------------
/mnt/hgfs/w_l_share/openal-soft-1.22.2/alc/backends/alsa.cpp: In member function ‘virtual void {anonymous}::AlsaPlayback::open(const char*)’:
/mnt/hgfs/w_l_share/openal-soft-1.22.2/alc/backends/alsa.cpp:643:70: error: cannot convert ‘al::optional<std::__cxx11::basic_string<char> >’ to ‘bool’ in initialization
         if(bool{driveropt = ConfigValueStr(nullptr, "alsa", "device")})
                                                                      ^
/mnt/hgfs/w_l_share/openal-soft-1.22.2/alc/backends/alsa.cpp: In member function ‘virtual void {anonymous}::AlsaCapture::open(const char*)’:
/mnt/hgfs/w_l_share/openal-soft-1.22.2/alc/backends/alsa.cpp:916:71: error: cannot convert ‘al::optional<std::__cxx11::basic_string<char> >’ to ‘bool’ in initialization
         if(bool{driveropt = ConfigValueStr(nullptr, "alsa", "capture")})
                                                                       ^
CMakeFiles/OpenAL.dir/build.make:1219: recipe for target 'CMakeFiles/OpenAL.dir/alc/backends/alsa.cpp.o' failed
make[2]: *** [CMakeFiles/OpenAL.dir/alc/backends/alsa.cpp.o] Error 1
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/OpenAL.dir/all' failed
make[1]: *** [CMakeFiles/OpenAL.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
-------------------------------------------------------------------------------
BUILD_LIBS=${HOME}/build_libs
 
export PATH=${BUILD_LIBS}/bin:${PATH}
export PKG_CONFIG_PATH=${BUILD_LIBS}/lib/pkgconfig:${PKG_CONFIG_PATH}
 
rm -rf build
mkdir build
cd build
 
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=${BUILD_LIBS} ..
 
make
make install

-------------------------------------------------------------------------------------------------
so how can i build it success ?

**Comment by kcat** [comment] 2022-07-25 07:12
This is a duplicate of #737 either way.

**Closed** 2022-07-25 07:12 UTC
