### ISSUE TITLE
Clicking sounds

### ISSUE THREAD

**Issue by ceski-1** [kcat/openal-soft#925] opened 2023-10-05 04:13 UTC
Here's a demonstration of the issue:

https://github.com/kcat/openal-soft/assets/56656010/2fffbb40-3dab-4f4c-83f3-fd7bd9f8c877

Tested Doom source ports (Win10 64-bit, 64-bit builds):
1. GZDoom 4.11.0, OpenAL Soft 1.22.1
2. GZDoom master, OpenAL Soft latest action
3. Woof master, OpenAL Soft 1.23.1 vcpkg
4. Woof master, OpenAL Soft latest action

Tested options (Woof only):
1. Resamplers: nearest, linear, cubic
2. OS sample rate: 44.1, 48, 96, 192 kHz

All of the above have clicking. These are workarounds that stop the clicking:
1. Force frequency to 22050 Hz using alsoft.ini. Not acceptable because it reduces the quality of custom 44.1 kHz sounds.
2. Use a hex editor (or a sound editor) to modify the sound file to fade-in over 8 samples (arbitrary number). Not practical.
3. Woof test branch: detect non-zero initial and final samples for each sound file. If detected, modify the data to use a fade-in/out. Do this prior to calling OpenAL Soft functions. Not a complete solution.

Ideally, OpenAL Soft should prevent clicking so these workarounds are not needed.

Additional details:
Most stock Doom sounds are 11025 Hz, 8-bit, mono. A couple are 22050 Hz. All of them start and/or end at a non-zero value (i.e. not at 128 for 8-bit), some worse than others. This is likely due to a poorly implemented "leading/trailing silence removal" step during mastering. The chaingunner is a good example because the sound is played repeatedly and the file has 3 moderately loud, non-zero samples at the start. Note: the original game with DOSBox Staging has no clicking issues.

[Here](https://github.com/kcat/openal-soft/files/12812042/click.zip) are two wads used in the video. clickfix.wad has a modified gun sound to prevent clicking. DOOM2.WAD required. Launch with:
```
gzdoom.exe -file click.wad -warp 1
or
woof.com -file click.wad -warp 1
```

**Comment by kcat** [comment] 2023-10-05 08:55
I'm not sure there's anything for OpenAL to do. It plays the samples its told to, and doesn't try to second-guess since there's always the possibility someone meant to play a sound like that. This would be more appropriately fixed on the game's side, either with a mod like that or some kind of engine-side fixup detecting the faulty sounds.

**Comment by ceski-1** [comment] 2023-10-05 12:58
In the past, OpenAL Soft had clicking issues with fixes to address them, but they seem to have been removed at some point. Was that a similar issue, with similar reasoning for removal?

**Comment by ceski-1** [comment] 2023-10-05 15:42
Possibly related? https://github.com/kcat/openal-soft/blob/23cc00ea16bdfbb06ae49cde0e05db6ec4a07100/core/voice.cpp#L861-L864

**Comment by kcat** [comment] 2023-10-05 20:45
> In the past, OpenAL Soft had clicking issues with fixes to address them, but they seem to have been removed at some point. Was that a similar issue, with similar reasoning for removal?

OpenAL Soft still has fixes for unintended clicking. Volume changes use a relatively quick per-sample ramp to avoid clicks caused by an immediate jump or dip in amplitude, stopping or pausing a sound will do an extra mix with a fade-out to avoid clicks caused by an immediate drop to 0 amplitude, starting a sound in the middle of a buffer will do a fade-in to avoid clicks caused by an immediate jump from 0 amplitude. However, the start of a buffer is assumed to be how the sound is intended to start, so doesn't do a fade-in (I did once experiment with doing a fade-in at the start of a buffer, but it had a negative effect on some sounds; dspistol was one of those sounds incidentally, the bang was severely dulled by the starting samples being lower than intended, and there'd be an obvious problem with an impulse sound that's just one non-0 sample at the start followed by silence).

> Possibly related?

Unlikely. That's intended to prevent clicking when a sound stops in the middle of playback. The problem with the sound is at the beginning, and OpenAL Soft assumes the samples at the beginning of a buffer are the intended samples to start with.

**Comment by ceski-1** [comment] 2023-10-05 23:26
> dspistol was one of those sounds incidentally, the bang was severely dulled

While working on a solution, I found that a 1 ms linear fade is good for minimizing clicks while being imperceptible. Some sounds require special handling (dsbospit is an infamous example).

> problem with an impulse sound that's just one non-0 sample at the start followed by silence

That's a good example and Doom's equivalent would be dstink which would sound different with any change. There are likely many other cases that have to be considered (looping sounds, etc.).

I appreciate the detailed response and your reasoning makes sense to me. I'll work on a solution on my end and close this issue.

**Closed** 2023-10-05 23:26 UTC
