### ISSUE TITLE
Does not build with C++20

### ISSUE THREAD

**Issue by neheb** [kcat/openal-soft#1068] opened 2024-11-20 23:39 UTC
A small glimpse:

```
../subprojects/openal-soft-1.24.0/core/helpers.cpp:47:15: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘const char8_t*’ [-Wformat=]
   47 |         TRACE("Searching %s for *%.*s\n", fpath.u8string().c_str(), al::sizei(ext), ext.data());
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                 |
      |                                                                 const char8_t*
../subprojects/openal-soft-1.24.0/core/logging.h:30:46: note: in definition of macro ‘TRACE’
   30 | #define TRACE(...) al_print(LogLevel::Trace, __VA_ARGS__)
      |                                              ^~~~~~~~~~~
../subprojects/openal-soft-1.24.0/core/helpers.cpp:47:27: note: format string is defined here
   47 |         TRACE("Searching %s for *%.*s\n", fpath.u8string().c_str(), al::sizei(ext), ext.data());
      |                          ~^
      |                           |
      |                           char*
      |                          %hhn
../subprojects/openal-soft-1.24.0/core/helpers.cpp:55:36: error: no matching function for call to ‘case_compare(std::u8string, const std::string_view&)’
   55 |                 && al::case_compare(entrypath.extension().u8string(), ext) == 0)
```

Basically, C++20 changes u8 in an incompatible way. See https://en.cppreference.com/w/cpp/language/character_literal --> 2

**Comment by kcat** [comment] 2024-11-22 20:41
These should be fixed with commit a2085cc745dca40891f01406315701dbc4fe873f. Are there any other errors?

**Comment by neheb** [comment] 2024-11-22 20:55
well, only warnings

std::filesystem::u8path is deprecated with C++20 confusingly enough.

Implicit this capture is also deprecated.

**Comment by neheb** [comment] 2024-11-22 20:58
this one is interesting:

```
../common/ringbuffer.h:23:55: warning: use of ‘std::hardware_destructive_interference_size’ [-Winterference-size]
   23 |     static constexpr std::size_t sCacheAlignment{std::hardware_destructive_interference_size};
      |                                                  ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/ringbuffer.h:23:55: note: its value can vary between compiler versions or with different ‘-mtune’ or ‘-mcpu’ flags
../common/ringbuffer.h:23:55: note: if this use is part of a public ABI, change it to instead use a constant variable you define
../common/ringbuffer.h:23:55: note: the default value for the current CPU tuning is 64 bytes
../common/ringbuffer.h:23:55: note: you can stabilize this value with ‘--param hardware_destructive_interference_size=64’, or disable this warning with ‘-Wno-interference-size’

```

**Comment by kcat** [comment] 2024-11-23 01:24
> std::filesystem::u8path is deprecated with C++20 confusingly enough.

Yeah, it expects you to use path() with the new `std::u8string[_view]` overload added in 20, while `u8path` takes a normal `std::string[_view]` and interprets it as a UTF-8 string (separate from the path() overload for `std::string[_view]`, which uses the system interpretation of `char` string names, that may or may not be UTF-8).

> this one is interesting:

It's somewhat telling when simply using a feature as intended results in a compiler warning (and four lines of notes) that needs to be expressly disabled.

**Closed** 2024-11-24 09:44 UTC
